baseURL = "https://techmuses.github.io"
languageCode = "en-us"
title = "techmuses"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "techmuses - All rights reserved"
enableEmoji = true
publishDir = "docs"
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"

[params]
  logo = "/images/logo.png"
  description ="things we learn"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "Akshay"
  thumbnail = "/images/author.png"
  description = "Creator of this blog."

[params.index]
  picture = "/images/author.jpg"
  title = "techmuses"
  subtitle = "A resource place to definitely keep an eye on"
  mdtext = '''
tehmuses is a smart,intelligent,quirky,witty content portal that targets people interested in technologies and computer and lets you grow with the knowledge of ours.
'''
  alertbar = false

[params.social]
  github = "< techmuses>"
  linkedin = "<username>"
  

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 200
    url = "/"

